DELETE FROM menu_items;
INSERT INTO menu_items (name, price, category, available) VALUES
  ('Lemon Juice', 20, 'Juices', true),
  ('Jal Jeera Lemon Juice', 25, 'Juices', true),
  ('Mosambi Juice', 50, 'Juices', true),
  ('Orange Juice', 50, 'Juices', true),
  ('Watermelon Juice', 50, 'Juices', true),
  ('Pineapple Juice', 50, 'Juices', true),
  ('Guava Juice', 50, 'Juices', true),
  ('Mara Mari Juice', 80, 'Juices', true),
  ('Ganga Yamuna', 60, 'Juices', true),
  ('Beat Carrot Juice', 50, 'Juices', true),
  ('Beetroot Carrot Anar Juice', 80, 'Juices', true),
  ('Beetroot Carrot Apple Juice', 80, 'Juices', true),
  ('Mosambi Anar Juice', 80, 'Juices', true),
  ('Pineapple/Mosambi/Anar Juice', 90, 'Juices', true),
  ('Guava/Pineapple/Mosambi Juice', 90, 'Juices', true),
  ('Watermelon Pineapple Juice', 80, 'Juices', true),
  ('Kiwi Juice', 70, 'Juices', true),
  ('Kiwi Lemon Juice', 80, 'Juices', true),
  ('Mosambi Guava Juice', 80, 'Juices', true),
  ('Mosambi/Pineapple/Apple Juice', 90, 'Juices', true),
  ('Watermelon Anar Juice', 80, 'Juices', true),
  ('Kiwi Mosambi Juice', 80, 'Juices', true),
  ('Mosambi/Dragon Fruit Juice', 90, 'Juices', true),
  ('Mosambi/Dragon Fruit/ Kiwi Juice', 100, 'Juices', true),
  ('Orange/Pineapple/Strawberry Juice', 100, 'Juices', true),
  ('Mosambi Apple Juice', 80, 'Juices', true),
  ('Mosambi Guava Pineapple Juice', 90, 'Juices', true),
  ('Mosambi Guava Anar Juice.', 90, 'Juices', true),
  ('Avocado Juice', 120, 'Juices', true),
  ('Mosambi Kiwi Pineapple Juice', 100, 'Juices', true),
  ('Mix Fruit Juice', 100, 'Juices', true),
  ('Fruit Plate', 50, 'Juices', true),
  ('Banana Milkshake', 50, 'Milkshakes', true),
  ('Chikoo Milkshake', 60, 'Milkshakes', true),
  ('Banana Chikoo Milkshake', 80, 'Milkshakes', true),
  ('Mango Milkshake', 90, 'Milkshakes', true),
  ('Mango Banana Milkshake', 100, 'Milkshakes', true),
  ('Apple Milkshake', 80, 'Milkshakes', true),
  ('Chocolate Milkshake', 70, 'Milkshakes', true),
  ('Oreo Milkshake', 100, 'Milkshakes', true),
  ('Kitkat Milkshake', 100, 'Milkshakes', true),
  ('Snickers Milkshake', 100, 'Milkshakes', true),
  ('Chikoo Chocolate Milkshake', 80, 'Milkshakes', true),
  ('Kitkat Banana Milkshake', 110, 'Milkshakes', true),
  ('Oreo Banana Milkshake', 110, 'Milkshakes', true),
  ('Papaya Milkshake', 60, 'Milkshakes', true),
  ('Muskmelon Milkshake', 60, 'Milkshakes', true),
  ('Chocolate Banana Milkshake', 80, 'Milkshakes', true),
  ('Chocolate With Ice Cream', 100, 'Milkshakes', true),
  ('Dragon Milkshake', 100, 'Milkshakes', true),
  ('Strawberry Milkshake', 90, 'Milkshakes', true),
  ('Strawberry Banana Milkshake', 100, 'Milkshakes', true),
  ('Strawberry Mango Milkshake', 100, 'Milkshakes', true),
  ('Dragon Fruit Banana Milkshake', 110, 'Milkshakes', true),
  ('Kaju Banana Milkshake', 120, 'Milkshakes', true),
  ('Chikoo Kaju Milkshake', 120, 'Milkshakes', true),
  ('Mango Badam Milkshake', 120, 'Milkshakes', true),
  ('Cold Coffee', 40, 'Milkshakes', true),
  ('Vanilla Cold Coffee', 120, 'Milkshakes', true),
  ('Caramel Cold Coffee', 120, 'Milkshakes', true),
  ('Hazelnut Cold Coffee', 120, 'Milkshakes', true),
  ('Avocado Milkshake', 120, 'Milkshakes', true),
  ('Coco Mint Cold Coffee', 120, 'Milkshakes', true),
  ('Rose Faluda', 130, 'Milkshakes', true),
  ('Kesar Falooda', 130, 'Milkshakes', true),
  ('Strawberry Falooda', 130, 'Milkshakes', true),
  ('Butterscotch Falooda', 130, 'Milkshakes', true),
  ('Banana Coffee Milkshake', 70, 'Milkshakes', true),
  ('Rose Milkshake', 50, 'Milkshakes', true),
  ('Kesar Milkshake', 50, 'Milkshakes', true),
  ('Butterscotch Milkshake', 50, 'Milkshakes', true),
  ('Bread Butter Toast', 30, 'Sandwich', true),
  ('Veg Sandwich', 40, 'Sandwich', true),
  ('Veg Toast Sandwich', 50, 'Sandwich', true),
  ('Veg Cheese Sandwich', 70, 'Sandwich', true),
  ('Veg Cheese Toast Sandwich', 70, 'Sandwich', true),
  ('Paneer Schezwan Toast', 70, 'Sandwich', true),
  ('Cheese Garlic Toast', 60, 'Sandwich', true),
  ('Cheese Garlic Corn Toast', 70, 'Sandwich', true),
  ('Cheese Garlic Capsicum Toast', 70, 'Sandwich', true),
  ('Cheese Toast', 60, 'Sandwich', true),
  ('Veg Grill Sandwich', 70, 'Sandwich', true),
  ('Veg Cheese Grill Sandwich', 100, 'Sandwich', true),
  ('Nutella Chocolate Toast Sandwich', 100, 'Sandwich', true),
  ('Masala Toast Sandwich', 70, 'Sandwich', true),
  ('Onion Capsicum Cheese Toast', 60, 'Sandwich', true),
  ('Cheese Capsicum Toast', 70, 'Sandwich', true),
  ('Paneer Garlic Toast', 70, 'Sandwich', true),
  ('Cheese Sandwich', 40, 'Sandwich', true),
  ('Bread Butter Jam Toast', 40, 'Sandwich', true),
  ('Cheese Chilli Toast', 70, 'Sandwich', true),
  ('Mayo Corn Capsicum Toast', 70, 'Sandwich', true),
  ('Veg Paneer Schezwan Toast', 80, 'Sandwich', true),
  ('Paneer Cheese Chilli Toast', 100, 'Sandwich', true),
  ('Veg Paneer Cheese Grill Sandwich', 100, 'Sandwich', true),
  ('Chicken Toast Sandwich', 60, 'Sandwich', true),
  ('Chicken Cheese Toast Sandwich', 80, 'Sandwich', true),
  ('Chicken Cheese Garlic Toast', 70, 'Sandwich', true),
  ('Chicken Mayo Toast', 70, 'Sandwich', true),
  ('Chicken Schezwan Toast', 90, 'Sandwich', true),
  ('Chicken Grill Sandwich', 90, 'Sandwich', true),
  ('Chicken Junglee Toast Sandwich', 60, 'Sandwich', true),
  ('Chicken Cheese Chilli Toast', 120, 'Sandwich', true),
  ('Omelet Toast Sandwich', 50, 'Sandwich', true),
  ('Chicken Pesto Toast Sandwich', 100, 'Sandwich', true),
  ('Veg Mushroom Cheese Pizza', 120, 'Pizzas And Burgers', true),
  ('Veg Mushroom Paneer Pizza', 120, 'Pizzas And Burgers', true),
  ('Veg Mushroom Corn Cheese Pizza', 100, 'Pizzas And Burgers', true),
  ('Veg Cheese Pizza', 100, 'Pizzas And Burgers', true),
  ('Veg Schezwan Cheese Pizza', 120, 'Pizzas And Burgers', true),
  ('Cheese Garlic Pizza', 100, 'Pizzas And Burgers', true),
  ('Veg Cheese Roll', 60, 'Pizzas And Burgers', true),
  ('Veg Cheese Burger', 60, 'Pizzas And Burgers', true),
  ('Garlic Corn Cheese Bread (5 pcs)', 110, 'Pizzas And Burgers', true),
  ('Paneer Garlic Cheese Bread (5 pcs)', 120, 'Pizzas And Burgers', true),
  ('Cheese Garlic Bread (5 pcs)', 100, 'Pizzas And Burgers', true),
  ('Chicken Cheese Pizza', 120, 'Pizzas And Burgers', true),
  ('Chicken Cheese Jalapeno Pizza', 130, 'Pizzas And Burgers', true),
  ('Chicken Cheese Garlic Pizza', 130, 'Pizzas And Burgers', true),
  ('Chicken Schezwan Cheese Pizza', 120, 'Pizzas And Burgers', true),
  ('Chicken Roll', 60, 'Pizzas And Burgers', true),
  ('Chicken Cheese Roll', 80, 'Pizzas And Burgers', true),
  ('Chicken Panini Roll', 70, 'Pizzas And Burgers', true),
  ('Chicken Mayo Cheese Pizza', 130, 'Pizzas And Burgers', true),
  ('Chicken Cheese Burger', 70, 'Pizzas And Burgers', true),
  ('Chicken Burger', 60, 'Pizzas And Burgers', true),
  ('Chicken Cheese Garlic Bread (5 pieces)', 120, 'Pizzas And Burgers', true),
  ('Perrie Chat', 50, 'Chaat Chaska', true),
  ('Bhel Puri', 35, 'Chaat Chaska', true),
  ('Sev Puri', 35, 'Chaat Chaska', true),
  ('Pani Puri', 30, 'Chaat Chaska', true),
  ('Masala Puri', 30, 'Chaat Chaska', true),
  ('Ragada Puri', 40, 'Chaat Chaska', true),
  ('Dahi Puri', 50, 'Chaat Chaska', true),
  ('Dahi Sev Puri', 50, 'Chaat Chaska', true),
  ('Cheese Bhel', 50, 'Chaat Chaska', true),
  ('Cheese Sev Puri', 50, 'Chaat Chaska', true),
  ('Sukha Bhel', 40, 'Chaat Chaska', true),
  ('Dahi Bhel Batata Chat', 50, 'Chaat Chaska', true),
  ('Delhi Chat', 50, 'Chaat Chaska', true),
  ('Papdi Chaat', 50, 'Chaat Chaska', true),
  ('Ragda Chaat', 50, 'Chaat Chaska', true),
  ('Aloo Tikki Chaat', 50, 'Chaat Chaska', true),
  ('Dahi Tikki', 50, 'Chaat Chaska', true),
  ('Ragda Pattice', 50, 'Chaat Chaska', true),
  ('Dahi Ragda Pattice', 60, 'Chaat Chaska', true),
  ('Dahi Kachori', 50, 'Chaat Chaska', true),
  ('Ragda Kachori', 50, 'Chaat Chaska', true),
  ('Samosa Bhel', 50, 'Chaat Chaska', true),
  ('Samosa Chaat', 50, 'Chaat Chaska', true),
  ('Cheeseling Chat (with chutney)', 50, 'Chaat Chaska', true),
  ('Cheeseling Chat (Cheese)', 50, 'Chaat Chaska', true),
  ('Basket Chat', 50, 'Chaat Chaska', true),
  ('Chole Tikki', 60, 'Chaat Chaska', true),
  ('Chole Samosa', 60, 'Chaat Chaska', true),
  ('Alfredo', 100, 'Pasta', true),
  ('Rosé', 100, 'Pasta', true),
  ('Pesto', 120, 'Pasta', true),
  ('Arrabiata', 100, 'Pasta', true),
  ('Lasagna', 120, 'Pasta', true),
  ('Mac N Cheese', 120, 'Pasta', true),
  ('Chicken Alfredo', 120, 'Pasta', true),
  ('Chicken Rosé', 120, 'Pasta', true),
  ('Chicken Pesto', 130, 'Pasta', true),
  ('Chicken Arrabiata', 120, 'Pasta', true),
  ('Jambalaya Arancini(Chicken)', 150, 'Pasta', true),
  ('Chicken Lasagna', 130, 'Pasta', true),
  ('Sada Dosa', 40, 'South Indian Corner', true),
  ('Butter Sada Dosa', 50, 'South Indian Corner', true),
  ('Cheese Sada Dosa', 60, 'South Indian Corner', true),
  ('Masala Dosa', 55, 'South Indian Corner', true),
  ('Mysore Masala Dosa', 70, 'South Indian Corner', true),
  ('Mysore Sada Dosa', 50, 'South Indian Corner', true),
  ('Schezwan Sada Dosa', 50, 'South Indian Corner', true),
  ('Spring Dosa', 80, 'South Indian Corner', true),
  ('Pav Bhaji Dosa', 80, 'South Indian Corner', true),
  ('Palak Cheese Dosa', 80, 'South Indian Corner', true),
  ('Palak Sada Dosa', 60, 'South Indian Corner', true),
  ('Schezwan Cheese', 80, 'South Indian Corner', true),
  ('Schezwan Masala', 65, 'South Indian Corner', true),
  ('Cheese Mysore Masala', 90, 'South Indian Corner', true),
  ('Sada Uthappa', 45, 'South Indian Corner', true),
  ('Onion Uthappa', 55, 'South Indian Corner', true),
  ('Tomato Onion Uttapam', 60, 'South Indian Corner', true),
  ('Medu Vada', 50, 'South Indian Corner', true),
  ('Idli Vada', 45, 'South Indian Corner', true),
  ('Idli Sambar', 40, 'South Indian Corner', true),
  ('Idli Butter', 50, 'South Indian Corner', true),
  ('Chole Bature', 75, 'South Indian Corner', true),
  ('Usal Misal Pav', 40, 'South Indian Corner', true),
  ('Paneer Sada Dosa', 70, 'South Indian Corner', true),
  ('Paneer Masala Dosa', 80, 'South Indian Corner', true),
  ('Paneer Capsicum Dosa', 80, 'South Indian Corner', true),
  ('Paneer Schezwan Dosa', 80, 'South Indian Corner', true),
  ('Neer Dosa Chutney', 60, 'South Indian Corner', true),
  ('Tufani Sada Dosa', 60, 'South Indian Corner', true),
  ('Tufani Masala Dosa', 80, 'South Indian Corner', true),
  ('Tufani Cheese Dosa', 80, 'South Indian Corner', true),
  ('Tufani Dancer Dosa', 90, 'South Indian Corner', true),
  ('Ragi Dosa', 60, 'South Indian Corner', true),
  ('Ragi Masala Dosa', 80, 'South Indian Corner', true),
  ('Ragi Mysore Masala Dosa', 80, 'South Indian Corner', true),
  ('Ragi Cheese Mysore Masala Dosa', 100, 'South Indian Corner', true),
  ('Ragi Cheese Dosa', 80, 'South Indian Corner', true),
  ('Pizza DosA', 100, 'South Indian Corner', true),
  ('Jini Dosa', 100, 'South Indian Corner', true),
  ('Noodle Dosa', 100, 'South Indian Corner', true),
  ('Dil Kush Uthappa', 100, 'South Indian Corner', true),
  ('Peri Peri Dosa', 80, 'South Indian Corner', true),
  ('Peri Peri Cheese Dosa', 100, 'South Indian Corner', true),
  ('Peri Peri Masala Dosa', 100, 'South Indian Corner', true),
  ('Sultani Dosa', 100, 'South Indian Corner', true),
  ('Set Dosa', 100, 'South Indian Corner', true),
  ('Rava Sada Dosa', 60, 'South Indian Corner', true),
  ('Rava Masala Dosa', 80, 'South Indian Corner', true),
  ('Rava Cheese Sada Dosa', 80, 'South Indian Corner', true),
  ('Rava Schezwan Masala Dosa', 100, 'South Indian Corner', true),
  ('Chocolate Dosa', 120, 'South Indian Corner', true),
  ('Paneer Sada', 60, 'South Indian Corner', true),
  ('Paneer Cheese Sada', 80, 'South Indian Corner', true),
  ('Paneer Masala Dosa', 80, 'South Indian Corner', true),
  ('Paneer Schezwan Masala Dosa', 100, 'South Indian Corner', true),
  ('Veg Uttapam', 80, 'South Indian Corner', true),
  ('Aloo Parata', 40, 'South Indian Corner', true),
  ('Paneer Parata', 50, 'South Indian Corner', true),
  ('Chicken Paratha', 50, 'South Indian Corner', true),
  ('Chicken Keema Paratha', 50, 'South Indian Corner', true),
  ('Chicken Cutlet Pav', 40, 'South Indian Corner', true),
  ('Chicken Bhature', 100, 'South Indian Corner', true),
  ('Honey Chilli Paneer Dry', 160, 'Chinese Starters', true),
  ('Paneer 65 (Dry/Gravy)', 150, 'Chinese Starters', true),
  ('Paneer Schezwan (Dry/Gravy)', 150, 'Chinese Starters', true),
  ('Paneer Chilli (Dry/Gravy)', 150, 'Chinese Starters', true),
  ('Paneer Crispy (Dry)', 150, 'Chinese Starters', true),
  ('Paneer Hot Garlic Sauce', 150, 'Chinese Starters', true),
  ('Paneer Sweet & Sour Sauce', 150, 'Chinese Starters', true),
  ('Paneer Manchurian(Dry/Gravy)', 140, 'Chinese Starters', true),
  ('Mushroom Chilly (Dry)', 150, 'Chinese Starters', true),
  ('Mushroom Manchurian (Dry/Gravy)', 120, 'Chinese Starters', true),
  ('Mushroom Chilly (Gravy)', 120, 'Chinese Starters', true),
  ('Mushroom 65 (Dry)', 120, 'Chinese Starters', true),
  ('Mushroom Schezwan (Dry/Gravy)', 120, 'Chinese Starters', true),
  ('Mushroom Garlic Sauce', 120, 'Chinese Starters', true),
  ('Mushroom Sweet Garlic Dry', 120, 'Chinese Starters', true),
  ('Mushroom Crispy (Dry)', 120, 'Chinese Starters', true),
  ('Mushroom Sweet Sour Sauce', 120, 'Chinese Starters', true),
  ('Mushroom Hot Garlic Sauce', 120, 'Chinese Starters', true),
  ('Corn Golden Dry', 100, 'Chinese Starters', true),
  ('Corn Chilli Dry', 120, 'Chinese Starters', true),
  ('Corn Crispy Dry', 120, 'Chinese Starters', true),
  ('Corn 65 Dry', 120, 'Chinese Starters', true),
  ('Corn Garlic Dry', 120, 'Chinese Starters', true),
  ('Corn Schezwan Dry', 120, 'Chinese Starters', true),
  ('Corn Baby Chilly', 120, 'Chinese Starters', true),
  ('Corn Sweet and Sour', 120, 'Chinese Starters', true),
  ('Veg Manchurian Dry', 120, 'Chinese Starters', true),
  ('Veg Manchurian Schezwan Dry', 150, 'Chinese Starters', true),
  ('Momos Steamed', 90, 'Chinese Starters', true),
  ('Momos Paneer Steamed', 90, 'Chinese Starters', true),
  ('Momo Chilly (Veg)', 100, 'Chinese Starters', true),
  ('Momo Chilly (Non-veg)', 120, 'Chinese Starters', true),
  ('C. Momo Dry (Veg/Non-veg)', 110, 'Chinese Starters', true),
  ('Momo Schezwan (Veg/Non-veg)', 110, 'Chinese Starters', true),
  ('Momo Sauce (Veg/Non-veg)', 60, 'Chinese Starters', true),
  ('Momo Chopsuey (Veg/Non-veg)', 110, 'Chinese Starters', true),
  ('Chicken Schezwan Roll', 60, 'Chinese Starters', true),
  ('Veg Schezwan Roll', 50, 'Chinese Starters', true),
  ('American Chopsuey', 100, 'Chinese Starters', true),
  ('Chinese Chopsuey', 100, 'Chinese Starters', true),
  ('Chicken American Chopsuey', 100, 'Chinese Starters', true),
  ('Chicken Chinese Chopsuey', 100, 'Chinese Starters', true),
  ('Lollipop Fry U.P.S.', 150, 'Chinese Starters', true),
  ('Lollypop Dry U.P.S.', 120, 'Chinese Starters', true),
  ('Lollipop Gravy', 120, 'Chinese Starters', true),
  ('Honey Chilli Chicken', 200, 'Chinese Starters', true),
  ('Chicken Salt & Pepper', 120, 'Chinese Starters', true),
  ('Chicken 65', 120, 'Chinese Starters', true),
  ('Chicken Crispy', 120, 'Chinese Starters', true),
  ('Chicken Tangdi Fry (per piece)', 50, 'Chinese Starters', true),
  ('Chicken Haddy Chilly', 120, 'Chinese Starters', true),
  ('Chicken Dice Chilly', 120, 'Chinese Starters', true),
  ('Chicken Sweet Garlic', 120, 'Chinese Starters', true),
  ('Prawns Golden Fry', 150, 'Chinese Starters', true),
  ('Prawns Koliwada', 150, 'Chinese Starters', true),
  ('Prawns Chilly', 150, 'Chinese Starters', true),
  ('Prawns Manchurian', 150, 'Chinese Starters', true),
  ('Prawns 65', 150, 'Chinese Starters', true),
  ('Prawns Schezwan', 150, 'Chinese Starters', true),
  ('Honey Chilli Prawns', 200, 'Chinese Starters', true),
  ('Prawns Hot & Sweet', 160, 'Chinese Starters', true),
  ('Prawns Hot Garlic', 160, 'Chinese Starters', true),
  ('Prawns Sweet & Sour', 160, 'Chinese Starters', true),
  ('Veg Triple Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Coriander Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Manchurian Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Mushroom Rice', 100, 'Chinese Rice And Noodles', true),
  ('Veg Singapore Rice', 100, 'Chinese Rice And Noodles', true),
  ('Veg Hong Kong Rice', 100, 'Chinese Rice And Noodles', true),
  ('Veg Thousand Rice', 150, 'Chinese Rice And Noodles', true),
  ('Veg Chopper Rice', 140, 'Chinese Rice And Noodles', true),
  ('Veg Combination Rice', 110, 'Chinese Rice And Noodles', true),
  ('Veg Manchow Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Paneer Fried Rice', 120, 'Chinese Rice And Noodles', true),
  ('Veg Paneer Tikka Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Chilli Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Italian Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Manchurian Dry', 130, 'Chinese Rice And Noodles', true),
  ('Veg Mushroom Dry', 130, 'Chinese Rice And Noodles', true),
  ('Paneer Chilli', 150, 'Chinese Rice And Noodles', true),
  ('Paneer Crispy', 120, 'Chinese Rice And Noodles', true),
  ('Veg Crispy', 90, 'Chinese Rice And Noodles', true),
  ('Veg American Chopsy', 100, 'Chinese Rice And Noodles', true),
  ('Veg Chinese Beal', 80, 'Chinese Rice And Noodles', true),
  ('Veg Garlic Rice', 100, 'Chinese Rice And Noodles', true),
  ('Veg Crispy Rice', 100, 'Chinese Rice And Noodles', true),
  ('Veg Momo Chilli Rice', 150, 'Chinese Rice And Noodles', true),
  ('Veg Chilli Rice', 140, 'Chinese Rice And Noodles', true),
  ('Veg Fried Momos', 100, 'Chinese Rice And Noodles', true),
  ('Veg Mumbai Special', 100, 'Chinese Rice And Noodles', true),
  ('Veg Chinese Thali', 140, 'Chinese Rice And Noodles', true),
  ('Veg Italian Rice', 130, 'Chinese Rice And Noodles', true),
  ('Veg Dragon Rice', 140, 'Chinese Rice And Noodles', true),
  ('Veg Malaysian Rice', 140, 'Chinese Rice And Noodles', true),
  ('Veg Sherpa Rice', 140, 'Chinese Rice And Noodles', true),
  ('Veg Green Chilli Rice', 140, 'Chinese Rice And Noodles', true),
  ('Veg Senri Rice', 140, 'Chinese Rice And Noodles', true),
  ('Hong Kong Noodles', 100, 'Chinese Rice And Noodles', true),
  ('Singapore Noodles', 100, 'Chinese Rice And Noodles', true),
  ('Mushroom Noodles', 110, 'Chinese Rice And Noodles', true),
  ('Garlic Noodles', 100, 'Chinese Rice And Noodles', true),
  ('Crispy Noodles', 110, 'Chinese Rice And Noodles', true),
  ('Triple Noodles', 130, 'Chinese Rice And Noodles', true),
  ('Combo Noodles', 110, 'Chinese Rice And Noodles', true),
  ('Mumbai Special Noodles', 110, 'Chinese Rice And Noodles', true),
  ('Paneer Schezwan Noodles', 130, 'Chinese Rice And Noodles', true),
  ('Chopper Noodles', 140, 'Chinese Rice And Noodles', true),
  ('Momo Chilli', 130, 'Chinese Rice And Noodles', true),
  ('Paneer chili momos', 130, 'Chinese Rice And Noodles', true),
  ('Spring roll', 50, 'Chinese Rice And Noodles', true),
  ('Chinese Ball', 80, 'Chinese Rice And Noodles', true),
  ('Crispy', 100, 'Chinese Rice And Noodles', true),
  ('Tu borg Pav', 60, 'Chinese Rice And Noodles', true),
  ('Veg Crispy Noodles', 100, 'Chinese Rice And Noodles', true),
  ('Veg Crispy Rice', 100, 'Chinese Rice And Noodles', true),
  ('Chicken Chinese Thali', 150, 'Chinese Rice And Noodles', true),
  ('Chicken American Chopsy', 100, 'Chinese Rice And Noodles', true),
  ('Chicken Chinese Beal', 90, 'Chinese Rice And Noodles', true),
  ('Chicken Chilli Rice', 150, 'Chinese Rice And Noodles', true),
  ('Chicken Mumbai Special', 100, 'Chinese Rice And Noodles', true),
  ('Chicken Triple Rice', 140, 'Chinese Rice And Noodles', true),
  ('Chicken Hong Kong Rice', 110, 'Chinese Rice And Noodles', true),
  ('Chicken Singapore Rice', 110, 'Chinese Rice And Noodles', true),
  ('Chicken Al King Rice', 150, 'Chinese Rice And Noodles', true),
  ('Chicken Shish Touk Rice', 120, 'Chinese Rice And Noodles', true),
  ('Chicken Fried Rice BBC', 120, 'Chinese Rice And Noodles', true),
  ('Veg Frankie', 50, 'Frankie Roll', true),
  ('Veg Cheese Frankie (Mayo)', 80, 'Frankie Roll', true),
  ('Veg Szechuan Frankie', 60, 'Frankie Roll', true),
  ('Noodle Frankie', 60, 'Frankie Roll', true),
  ('Noodle Cheese/Mayo Frankie', 80, 'Frankie Roll', true),
  ('Noodle Szechuan Frankie', 70, 'Frankie Roll', true),
  ('Mix Special Frankie', 90, 'Frankie Roll', true),
  ('Paneer Frankie', 70, 'Frankie Roll', true),
  ('Paneer Cheese/Mayo Frankie', 90, 'Frankie Roll', true),
  ('Paneer Szechuan Frankie', 90, 'Frankie Roll', true),
  ('Manchurian Frankie', 80, 'Frankie Roll', true),
  ('Manchurian Cheese/Mayo Frankie', 90, 'Frankie Roll', true),
  ('Manchurian Szechuan Frankie', 80, 'Frankie Roll', true),
  ('Paneer Chilli Frankie', 90, 'Frankie Roll', true),
  ('Paneer Chilli Cheese/Mayo Frankie', 100, 'Frankie Roll', true),
  ('Chinese Bhel Frankie', 80, 'Frankie Roll', true),
  ('Chinese Bhel Cheese/Mayo Frankie', 100, 'Frankie Roll', true),
  ('Mix Special Manchurian Paneer Frankie', 120, 'Frankie Roll', true),
  ('Pizza Frankie', 90, 'Frankie Roll', true),
  ('Pizza Paneer Frankie', 100, 'Frankie Roll', true),
  ('Veg Corn Frankie', 60, 'Frankie Roll', true),
  ('Veg Cheese Corn Frankie', 80, 'Frankie Roll', true),
  ('Veg Corn Paneer Cheese Mayo Szechuan Frankie', 100, 'Frankie Roll', true),
  ('Egg Fring', 60, 'Frankie Roll', true),
  ('Egg Cheese/Mayo Frankie', 80, 'Frankie Roll', true),
  ('Egg Szechuan Frankie', 70, 'Frankie Roll', true),
  ('Egg Paneer Cheese/Mayo Frankie', 100, 'Frankie Roll', true),
  ('Egg Veg Frankie', 80, 'Frankie Roll', true),
  ('Egg Noodle Frankie', 80, 'Frankie Roll', true),
  ('Egg Manchurian Frankie', 100, 'Frankie Roll', true),
  ('Chicken Noodle Frankie', 90, 'Frankie Roll', true),
  ('Chicken Frankie', 70, 'Frankie Roll', true),
  ('Chicken Cheese Frankie', 90, 'Frankie Roll', true),
  ('Chicken Mayo Frankie', 80, 'Frankie Roll', true),
  ('Chicken Szechuan Frankie', 80, 'Frankie Roll', true),
  ('Chicken Dragon Frankie', 80, 'Frankie Roll', true),
  ('Chicken Manchurian Fry', 110, 'Frankie Roll', true),
  ('Pav Bhaji', 70, 'Pav Bhaji', true),
  ('Butter Pav Bhaji', 80, 'Pav Bhaji', true),
  ('Cheese Pav Bhaji', 90, 'Pav Bhaji', true),
  ('Masala Pav', 70, 'Pav Bhaji', true),
  ('Cheese Masala Pav', 90, 'Pav Bhaji', true),
  ('Butter Masala Pav', 80, 'Pav Bhaji', true),
  ('Mushroom Pav Bhaji', 80, 'Pav Bhaji', true),
  ('Paneer Pav Bhaji', 80, 'Pav Bhaji', true),
  ('Tawa Pulav', 70, 'Pav Bhaji', true),
  ('Sada Pulav', 70, 'Pav Bhaji', true),
  ('Butter Pulav', 80, 'Pav Bhaji', true),
  ('Cheese Pulav', 90, 'Pav Bhaji', true),
  ('Butter Cheese Pulav', 100, 'Pav Bhaji', true),
  ('Mushroom Pulav', 80, 'Pav Bhaji', true),
  ('Paneer Pulav', 80, 'Pav Bhaji', true),
  ('Hyderabadi Tea Cutting', 10, 'Chai Adda', true),
  ('Hyderabadi Tea Full', 20, 'Chai Adda', true),
  ('Elaichi Tea Cutting', 10, 'Chai Adda', true),
  ('Elaichi Tea Full', 20, 'Chai Adda', true),
  ('Masala Tea Cutting', 10, 'Chai Adda', true),
  ('Masala Tea Full', 20, 'Chai Adda', true),
  ('Ginger Tea Cutting', 10, 'Chai Adda', true),
  ('Ginger Tea Full', 20, 'Chai Adda', true),
  ('Black Tea', 10, 'Chai Adda', true),
  ('Filter Coffee Cutting', 15, 'Chai Adda', true),
  ('Green Tea with Honey Mint', 20, 'Chai Adda', true),
  ('Lemon Tea with Honey Mint', 20, 'Chai Adda', true),
  ('Kesari Ukala', 25, 'Chai Adda', true),
  ('Milk', 25, 'Chai Adda', true),
  ('Badam Milk', 25, 'Chai Adda', true),
  ('Boost', 25, 'Chai Adda', true),
  ('Bournvita', 25, 'Chai Adda', true),
  ('Horlicks', 25, 'Chai Adda', true),
  ('Hot Chocolate', 25, 'Chai Adda', true),
  ('Lemon Iced Tea', 35, 'Chai Adda', true),
  ('Sheera', 35, 'Breakfast Counter', true),
  ('Poha', 30, 'Breakfast Counter', true),
  ('Upma', 30, 'Breakfast Counter', true),
  ('Double Omlet Pav (2Pcs)', 50, 'Breakfast Counter', true),
  ('Double Bhurji Pav (2Pcs)', 60, 'Breakfast Counter', true),
  ('Egg Burma', 60, 'Breakfast Counter', true),
  ('Aloo Paratha', 50, 'Breakfast Counter', true),
  ('French Toast', 70, 'Breakfast Counter', true),
  ('Boiled Egg', 12, 'Breakfast Counter', true),
  ('Irani Omelette', 50, 'Breakfast Counter', true),
  ('Garlic Toast (2ps)', 30, 'Breakfast Counter', true),
  ('Maggi', 40, 'Breakfast Counter', true),
  ('Cheese Maggi', 50, 'Breakfast Counter', true),
  ('Veg Maggi', 50, 'Breakfast Counter', true),
  ('Bread Butter Toast', 20, 'Breakfast Counter', true),
  ('Bun Maska/Jam', 20, 'Breakfast Counter', true),
  ('Veg Lunch', 80, 'Lunch Counter', true),
  ('½ Veg Biryani', 60, 'Lunch Counter', true),
  ('½ Veg Pulav', 60, 'Lunch Counter', true),
  ('½ Jeera Rice', 60, 'Lunch Counter', true),
  ('Malabar Parotta', 20, 'Lunch Counter', true),
  ('Rajma Rice', 60, 'Lunch Counter', true),
  ('Non-Veg Lunch', 140, 'Lunch Counter', true),
  ('Chicken Biryani', 140, 'Lunch Counter', true),
  ('½ Chicken Biryani', 90, 'Lunch Counter', true),
  ('Chicken Keema', 60, 'Lunch Counter', true),
  ('Chicken Masala', 75, 'Lunch Counter', true),
  ('Butter Chicken', 75, 'Lunch Counter', true),
  ('Double Egg Rice', 80, 'Lunch Counter', true),
  ('Chana Masala', 35, 'Lunch Counter', true),
  ('Rajma Masala', 35, 'Lunch Counter', true),
  ('Sukha Bhaji', 30, 'Lunch Counter', true),
  ('Paneer Masala', 50, 'Lunch Counter', true),
  ('Peri Peri Masala French Fries', 85, 'Snacks', true),
  ('French Fries', 70, 'Snacks', true),
  ('Cheese French Fries', 90, 'Snacks', true),
  ('Peri Peri & Cheese French Fries', 100, 'Snacks', true),
  ('Wedges', 80, 'Snacks', true),
  ('Chilli Garlic', 80, 'Snacks', true),
  ('Cheese Shotz', 90, 'Snacks', true),
  ('Double Egg Bhurji', 60, 'Snacks', true),
  ('Double Omelette', 50, 'Snacks', true),
  ('Double Egg Fry', 50, 'Snacks', true),
  ('Double Egg Schezwan Omelette', 60, 'Snacks', true);